require('normalize.css');
require('./lib/forms.css');
require('./lib/global.css');
require('./lib/headings.css');
require('./lib/links.css');
require('./lib/lists.css');
require('./lib/media.css');
require('./lib/misc.css');
require('./lib/text.css');
